import { type TeamInfo } from "./types"

export const NBA_TEAMS: TeamInfo[] = [
  { abbr: "ATL", city: "Atlanta", name: "Hawks", espnId: 1 },
  { abbr: "BOS", city: "Boston", name: "Celtics", espnId: 2 },
  { abbr: "NOP", city: "New Orleans", name: "Pelicans", espnId: 3 },
  { abbr: "CHI", city: "Chicago", name: "Bulls", espnId: 4 },
  { abbr: "CLE", city: "Cleveland", name: "Cavaliers", espnId: 5 },
  { abbr: "DAL", city: "Dallas", name: "Mavericks", espnId: 6 },
  { abbr: "DEN", city: "Denver", name: "Nuggets", espnId: 7 },
  { abbr: "DET", city: "Detroit", name: "Pistons", espnId: 8 },
  { abbr: "GSW", city: "Golden State", name: "Warriors", espnId: 9 },
  { abbr: "HOU", city: "Houston", name: "Rockets", espnId: 10 },
  { abbr: "IND", city: "Indiana", name: "Pacers", espnId: 11 },
  { abbr: "LAC", city: "LA", name: "Clippers", espnId: 12 },
  { abbr: "LAL", city: "Los Angeles", name: "Lakers", espnId: 13 },
  { abbr: "MIA", city: "Miami", name: "Heat", espnId: 14 },
  { abbr: "MIL", city: "Milwaukee", name: "Bucks", espnId: 15 },
  { abbr: "MIN", city: "Minnesota", name: "Timberwolves", espnId: 16 },
  { abbr: "BKN", city: "Brooklyn", name: "Nets", espnId: 17 },
  { abbr: "NYK", city: "New York", name: "Knicks", espnId: 18 },
  { abbr: "ORL", city: "Orlando", name: "Magic", espnId: 19 },
  { abbr: "PHI", city: "Philadelphia", name: "76ers", espnId: 20 },
  { abbr: "PHX", city: "Phoenix", name: "Suns", espnId: 21 },
  { abbr: "POR", city: "Portland", name: "Trail Blazers", espnId: 22 },
  { abbr: "SAC", city: "Sacramento", name: "Kings", espnId: 23 },
  { abbr: "SAS", city: "San Antonio", name: "Spurs", espnId: 24 },
  { abbr: "OKC", city: "Oklahoma City", name: "Thunder", espnId: 25 },
  { abbr: "UTA", city: "Utah", name: "Jazz", espnId: 26 },
  { abbr: "WAS", city: "Washington", name: "Wizards", espnId: 27 },
  { abbr: "TOR", city: "Toronto", name: "Raptors", espnId: 28 },
  { abbr: "MEM", city: "Memphis", name: "Grizzlies", espnId: 29 },
  { abbr: "CHA", city: "Charlotte", name: "Hornets", espnId: 30 },
]
