import { type Game } from "./types"

export const MOCK_GAMES_PAGE_2: Game[] = [
  {
    id: "7",
    awayTeam: "PHX",
    homeTeam: "SAC",
    date: "May 24",
    time: "9:30 PM",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
  },
  {
    id: "8",
    awayTeam: "DAL",
    homeTeam: "MIN",
    date: "May 24",
    time: "8:00 PM",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
  },
  {
    id: "9",
    awayTeam: "CLE",
    homeTeam: "ORL",
    date: "May 25",
    time: "7:00 PM",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
  },
  {
    id: "10",
    awayTeam: "CHI",
    homeTeam: "TOR",
    date: "May 25",
    time: "7:30 PM",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
  },
]

export const MOCK_GAMES: Game[] = [
  {
    id: "1",
    awayTeam: "BOS",
    homeTeam: "NYK",
    date: "May 22",
    time: "7:30 PM",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
  },
  {
    id: "2",
    awayTeam: "LAL",
    homeTeam: "GSW",
    date: "May 22",
    time: "10:00 PM",
    homeScore: 108,
    awayScore: 104,
    status: "live",
  },
  {
    id: "3",
    awayTeam: "MIA",
    homeTeam: "BOS",
    date: "May 21",
    time: "8:00 PM",
    homeScore: 112,
    awayScore: 99,
    status: "final",
  },
  {
    id: "4",
    awayTeam: "DEN",
    homeTeam: "OKC",
    date: "May 23",
    time: "9:00 PM",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
  },
  {
    id: "5",
    awayTeam: "NYK",
    homeTeam: "PHI",
    date: "May 23",
    time: "7:00 PM",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
  },
  {
    id: "6",
    awayTeam: "MIL",
    homeTeam: "IND",
    date: "May 21",
    time: "7:00 PM",
    homeScore: 120,
    awayScore: 115,
    status: "final",
  },
]
